# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Publish package to pub.dev

on:
  release:
    types:
      - created

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.38.8'

      - name: Setup Credentials
        uses: joutvhu/write-file@v1
        with:
          path: ~/.pub-cache/credentials.json
          contents: ${{ secrets.PUB_CREDENTIALS }}
          write_mode: overwrite

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze and Dry Run
        run: |
          flutter analyze
          flutter pub publish --dry-run

      - name: Publish to Pub.dev
        run: flutter pub publish --force
